import React from "react";
import { createRoot } from "react-dom/client";

function App() {
  return (
    <main style={{ fontFamily: "sans-serif", padding: 24 }}>
      <h1>Omni Sentinal UI</h1>
      <p>Template-generated by Install_command_v7.</p>
    </main>
  );
}

createRoot(document.getElementById("root")).render(<App />);
